### ISSUE TITLE
Cover component not detected

### ISSUE THREAD

**Issue by Tungsteno74** [payano/homeassist-ng#14]
Hello @payano,
i'm trying your good app and found that Cover component seem not to be shown in your app.

The configuration.yaml part is:
```
cover:
  - platform: npi_gpio
    relay_time: 1
    invert_relay: true
    covers:
      - relay_pin: 8
        state_pin: 10
        name: 'Dx cover'
```
this work well on the web interface.
